version: '2'
services:
  #mesin1 -- copykan untuk mesin 2,3, dst
  mesin1:
    network_mode : host
    container_name: ds-mesin-1
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "JPORT=34001"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
  mesin2:
    container_name: ds-mesin-2
    network_mode : host
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "JPORT=34002"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
  mesin3:
    container_name: ds-mesin-3
    network_mode : host
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "JPORT=34003"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
  mesin4:
    container_name: ds-mesin-4
    network_mode : host
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "JPORT=34004"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
  mesin5:
    container_name: ds-mesin-5
    network_mode : host
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "JPORT=34005"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"

